services:
  app:
    build: .
    container_name: gossip
    restart: always
    ports:
      - "7001:7001"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DB_URL: mongodb://mongo:27017/Chat
  mongo:
    image: mongo:4.4
    container_name: gossip-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
